# Generated by Django 6.0.1 on 2026-01-19 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Unique identifier code', max_length=50, unique=True)),
                ('layer', models.IntegerField(choices=[(1, 'Layer 1 - Top Level'), (2, 'Layer 2'), (3, 'Layer 3'), (4, 'Layer 4'), (5, 'Layer 5 - Bottom Level')], default=1)),
                ('description', models.TextField(blank=True)),
                ('head_name', models.CharField(blank=True, help_text='Name of the unit head', max_length=200)),
                ('head_title', models.CharField(blank=True, help_text='Title of the unit head', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent organizational unit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.organizationalunit')),
            ],
            options={
                'verbose_name': 'Organizational Unit',
                'verbose_name_plural': 'Organizational Units',
                'ordering': ['layer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, help_text='Job level or grade', max_length=50)),
                ('required_qualifications', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizational_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organization.organizationalunit')),
            ],
            options={
                'ordering': ['organizational_unit', 'title'],
            },
        ),
    ]
